// @ts-nocheck
import { formatDate } from '@angular/common';
export class Incidence {
  dutySlipID: number;
  userID: number;
  reservationID: number;
  customerID:number;
  incidenceID: number;
  passengerID: number;
  inventoryID: number;
  driverID: number;
  customerpersonName:string;
  incidenceDate: Date ;
  incidenceTime: Date;
  incidenceDateString: string;
  incidenceTimeString: string;
  incidencePlace: string;
  dispatchLocationID: number;
  incidenceTypeID: number;
  issueCategoryID: number;
  incidenceDetails: string;
  reportingDateString: string;
  reportingDate: Date;
  reportingTime: Date;
  reportingTimeString: string;
  reportedBy: string;
  reporterName: string;
  reportSource: string;
  reportEvidenceDoc: string;
  assignedToEmployeeID: number;
  assignedToEmployeeDepartment: string;
  openedByEmployeeID: number;
  openedByEmployeeName: string;
  openedByEmployeeDepartment: string;
  openDateString: string;
  openDate: Date | null;
  openTime: Date | null;
  openTimeString: string;
  closedByEmployeeID: number;
  rootCauseAnalysis: string;
  actionTaken: string;
  closureComment: string;
  closureDate: Date | null;
  closureTime: Date | null;
  closureDateString: string;
  closureTimeString: string;
  incidenceCategory: string;
  responsible1DriverID: number;
  responsible1VendorID: number;
  responsible1EmployeeID: number;
  responsible1CustomerPersonID: number;
  responsible2: string;
  assignedToEmployeeName: string;
  dutySlipNumber: string;
  incidenceType: string;
  customerPersonName: string;
  issueCategory: string;
  responsible2DriverID: number;
  responsible2EmployeeID: number;
  responsible2CustomerPersonID: number;
  responsible3: string;
  registrationNumber: string;
  driverName: string;
  locationOutAddressString: string;
  responsible3DriverID: number;
  responsible3VendorID: number;
  responsible3EmployeeID: number;
  responsible3CustomerPersonID: number;
  responsible4: string;
  responsible4DriverID: number;
  responsible4VendorID: number;
  responsible4EmployeeID: number;
  responsible4CustomerPersonID: number;
  activationStatus: boolean | null;
  customerName:string;
  dispatchLocation:string;
  responsible1:string;
  responsible1EmployeeName:string
  incidenceEmailAcknowledged:boolean;
  feedbackEmailAcknowledged:boolean;
  Responsible1Name:string;
  closedByEmployee:string;
  customerType:string;
  supplier:string;
  isVIP:string;
  department:string;
  type:string;
  constructor(incidence) {
    this.dutySlipID = incidence.dutySlipID || '';
    this.userID = incidence.userID || '';
    this.reservationID = incidence.reservationID || '';
    this.incidenceID = incidence.incidenceID || -1;
    this.passengerID = incidence.passengerID || '';
    this.inventoryID = incidence.inventoryID || '';
    this.driverID = incidence.driverID || '';
    this.incidenceDate = incidence.incidenceDate || null;
    this.incidenceTime = incidence.incidenceTime || null;
    this.incidenceDateString = incidence.incidenceDateString || '';
    this.incidenceTimeString = incidence.incidenceTimeString || '';
    this.incidencePlace = incidence.incidencePlace || '';
    this.dispatchLocationID = incidence.dispatchLocationID || '';
    this.incidenceTypeID = incidence.incidenceTypeID || '';
    this.issueCategoryID = incidence.issueCategoryID || '';
    this.incidenceDetails = incidence.incidenceDetails || '';
    this.reportingDateString = incidence.reportingDateString || '';
    this.reportingDate = incidence.reportingDate || null;
    this.reportingTime = incidence.reportingTime || null;
    this.reportingTimeString = incidence.reportingTimeString || '';
    this.reportedBy = incidence.reportedBy || '';
    this.reporterName = incidence.reporterName || '';
    this.reportSource = incidence.reportSource || '';
    this.incidenceEmailAcknowledged = incidence.incidenceEmailAcknowledged || '';
    this.feedbackEmailAcknowledged = incidence.feedbackEmailAcknowledged || '';
    this.reportEvidenceDoc = incidence.reportEvidenceDoc || '';
    this.assignedToEmployeeID = incidence.assignedToEmployeeID || '';
   this.openedByEmployeeName = incidence.openedByEmployeeName || '';
    this.assignedToEmployeeDepartment = incidence.assignedToEmployeeDepartment || '';
    this.openedByEmployeeID = incidence.openedByEmployeeID || '';
    this.openedByEmployeeDepartment = incidence.openedByEmployeeDepartment || '';
    this.openDateString = incidence.openDateString || '';
    this.openDate = incidence.openDate || null;
    this.openTime = incidence.openTime || null;
    this.openTimeString = incidence.openTimeString || '';
    this.dispatchLocation = incidence.dispatchLocation || '';
    this.closedByEmployeeID = incidence.closedByEmployeeID || '';
    this.rootCauseAnalysis = incidence.rootCauseAnalysis || '';
    this.actionTaken = incidence.actionTaken || '';
    this.closureComment = incidence.closureComment || '';
    this.closureDate = incidence.closureDate || null;
    this.closureTime = incidence.closureTime || null;
    this.closureDateString = incidence.closureDateString || '';
    this.closureTimeString = incidence.closureTimeString || '';
    this.incidenceCategory = incidence.incidenceCategory || '';
    this.responsible1DriverID = incidence.responsible1DriverID || '';
    this.responsible1VendorID = incidence.responsible1VendorID || '';
    this.responsible1EmployeeID = incidence.responsible1EmployeeID || '';
    this.responsible1CustomerPersonID = incidence.responsible1CustomerPersonID || '';
    this.responsible2 = incidence.responsible2 || '';
    this.responsible2DriverID = incidence.responsible2DriverID || '';
    this.responsible2EmployeeID = incidence.responsible2EmployeeID || '';
    this.responsible2CustomerPersonID = incidence.responsible2CustomerPersonID || '';
    this.responsible3 = incidence.responsible3 || '';
    this.responsible3DriverID = incidence.responsible3DriverID || '';
    this.responsible3VendorID = incidence.responsible3VendorID || '';
    this.responsible3EmployeeID = incidence.responsible3EmployeeID || '';
    this.responsible3CustomerPersonID = incidence.responsible3CustomerPersonID || '';
    this.responsible4 = incidence.responsible4 || '';
    this.responsible4DriverID = incidence.responsible4DriverID || '';
    this.responsible4VendorID = incidence.responsible4VendorID || '';
    this.responsible4EmployeeID = incidence.responsible4EmployeeID || '';
    this.responsible4CustomerPersonID = incidence.responsible4CustomerPersonID || '';
    this.activationStatus = incidence.activationStatus || null;
    this.incidenceDate=new Date();
    this.incidenceTime=new Date();
    this.reportingDate= new Date();
    this.reportingTime= new Date();
    this.department = incidence.department || '';
     this.type = incidence.type || '';
  }
}


