// @ts-nocheck
import { formatDate } from '@angular/common';
export class AppDutyMIS {
  bookingNo: string;
  dutySlipNo: string;
  dutyDate: Date;
  dispatchLocation: string;
  driverName: string;
  carNo: string;
  customerID: number;
  appGarageToStartKm: string;
  appPickToEndKm: string;
  appEndToGarageKm: string;
  locationOutKm: string;
  reportingKm: string;
  releasingKm: string;
  locationInKm: string;
  appGtracKm: string;
  locationOutTime: string;
  reportingTime: string;
  releasingTime: string;
  locationInTime: string;
  appLotTime: string;
  appReachedTime: string;
  appTripStartTime: string;
  appReleasingTime: string;
  appGarageInTime: string;
  appLocationOutAddress: string;
  appReachedPickupAddress: string;
  appTripStartAddress: string;
  appTripEndAddress: string;
  appVersion: string;
  mobile: string;
  deviceModel: string;
  tripStatus: string;
  dutyDispatchFrom: string;
  dutyGoingOn: string;
  typeOfSupplier: string;
  supplierName: string;
  groupName: string;
  onCallDedi: string;
  dutyType: string;
  carBooked: string;
  actualEndTime: Date;
  totalHrs: number;
  totalKms: number;
  appLocationInTime: string;
  bookingEventType: string;
  guestSignature: string;
  organizationalEntityName: string;

  constructor(appDutyMIS: any) {
    this.bookingNo = appDutyMIS.bookingNo || '';
    this.dutySlipNo = appDutyMIS.dutySlipNo || '';
    this.dutyDate = appDutyMIS.dutyDate ? new Date(appDutyMIS.dutyDate) : null;
    this.dispatchLocation = appDutyMIS.dispatchLocation || '';
    this.driverName = appDutyMIS.driverName || '';
    this.carNo = appDutyMIS.carNo || '';
    this.customerID = appDutyMIS.customerID || 0;
    this.appGarageToStartKm = appDutyMIS.appGarageToStartKm || '';
    this.appPickToEndKm = appDutyMIS.appPickToEndKm || '';
    this.appEndToGarageKm = appDutyMIS.appEndToGarageKm || '';
    this.locationOutKm = appDutyMIS.locationOutKm || '';
    this.reportingKm = appDutyMIS.reportingKm || '';
    this.releasingKm = appDutyMIS.releasingKm || '';
    this.locationInKm = appDutyMIS.locationInKm || '';
    this.appGtracKm = appDutyMIS.appGtracKm || '';
    this.locationOutTime = appDutyMIS.locationOutTime || '';
    this.reportingTime = appDutyMIS.reportingTime || '';
    this.releasingTime = appDutyMIS.releasingTime || '';
    this.locationInTime = appDutyMIS.locationInTime || '';
    this.appLotTime = appDutyMIS.appLotTime || '';
    this.appReachedTime = appDutyMIS.appReachedTime || '';
    this.appTripStartTime = appDutyMIS.appTripStartTime || '';
    this.appReleasingTime = appDutyMIS.appReleasingTime || '';
    this.appGarageInTime = appDutyMIS.appGarageInTime || '';
    this.appLocationOutAddress = appDutyMIS.appLocationOutAddress || '';
    this.appReachedPickupAddress = appDutyMIS.appReachedPickupAddress || '';
    this.appTripStartAddress = appDutyMIS.appTripStartAddress || '';
    this.appTripEndAddress = appDutyMIS.appTripEndAddress || '';
    this.appVersion = appDutyMIS.appVersion || '';
    this.mobile = appDutyMIS.mobile || '';
    this.deviceModel = appDutyMIS.deviceModel || '';
    this.tripStatus = appDutyMIS.tripStatus || '';
    this.dutyDispatchFrom = appDutyMIS.dutyDispatchFrom || '';
    this.dutyGoingOn = appDutyMIS.dutyGoingOn || '';
    this.typeOfSupplier = appDutyMIS.typeOfSupplier || '';
    this.supplierName = appDutyMIS.supplierName || '';
    this.groupName = appDutyMIS.groupName || '';
    this.onCallDedi = appDutyMIS.onCallDedi || '';
    this.dutyType = appDutyMIS.dutyType || '';
    this.carBooked = appDutyMIS.carBooked || '';
    this.actualEndTime = appDutyMIS.actualEndTime ? new Date(appDutyMIS.actualEndTime) : null;
    this.totalHrs = appDutyMIS.totalHrs || 0;
    this.totalKms = appDutyMIS.totalKms || 0;
    this.appLocationInTime = appDutyMIS.appLocationInTime || '';
    this.bookingEventType = appDutyMIS.bookingEventType || '';
    this.guestSignature = appDutyMIS.guestSignature || '';
  }
}


