// @ts-nocheck
import { formatDate } from '@angular/common';
export class DriverMIS {
  driverID: number;
  driverName: string;
  driverGradeID: number;
  driverFatherName: string;
  driverGrade: string;
  driverEmail: string;
  driverOfficialIdentityNumber: string;
  aadharAuthenticationToken: string;
  dob: Date;
  dobString: string;
  driverGradeName: string;
  rtoState: string;
  password: string;
  confirmPassword: string;
  idMark: string;
  localAddressCity: string;
  highestQualificationID: number;
  highestQualification: string;
  bloodGroup: string;
  driverStatus: string;
  dateOfJoining: Date;
  dateOfJoiningString: string;
  dateOfLeaving: Date;
  dateOfLeavingString: string;
  localAddressAddressString: string;
  localAddressLatLong: string;
  localAddressCityID: number;
  localAddress: string;
  localPincode: string;
  permanentAddressCityID: number;
  permanentAddressCity: string;
  permanentAddress: string;
  permanentAddressPincode: string;
  mobile1: string;
  mobile2: string;
  hubID: number;
  hub: string;
  locationID: number;
  location: string;
  supplierType: string;
  supplierTypeID: number;
  supplierID: number;
  supplier: string;
  englishSpeakingSkills: string;
  referenceOf: string;
  rtoStateID: number;
  policeVerification: string;
  driverImage: string;
  medicalInsurance: boolean;
  drivingSinceDate: Date;
  drivingSinceDateString: string;
  countryCodes: string;
  activationStatus: boolean;
  latitude: string;
  longitude: string;
  companyName: string;
  companyID: number;
  userID: number;
  driverFeedbackAverage: string;
  driverFeedbackReceived: string;
  driverFeedbackTotal: string;
  driverFeedbackCount: string;
  appLoginStatus: string;
  offDuty: string;
  appVersion: string;
  deviceModel: string;
  deviceIMEI: string;
  deviceType: string;
  driverCameraProblem: string;

  constructor(driverMIS: any) {
    this.driverID = driverMIS.driverID || -1;
    this.driverName = driverMIS.driverName || '';
    this.driverGradeID = driverMIS.driverGradeID || '';
    this.driverFatherName = driverMIS.driverFatherName || '';
    this.driverGrade = driverMIS.driverGrade || '';
    this.driverEmail = driverMIS.driverEmail || '';
    this.driverOfficialIdentityNumber = driverMIS.driverOfficialIdentityNumber || '';
    this.aadharAuthenticationToken = driverMIS.aadharAuthenticationToken || '';
    this.dob = new Date(driverMIS.dob) || new Date();
    this.dobString = driverMIS.dobString || '';
    this.driverGradeName = driverMIS.driverGradeName || '';
    this.rtoState = driverMIS.rtoState || '';
    this.password = driverMIS.password || '';
    this.confirmPassword = driverMIS.confirmPassword || '';
    this.idMark = driverMIS.idMark || '';
    this.localAddressCity = driverMIS.localAddressCity || '';
    this.highestQualificationID = driverMIS.highestQualificationID || '';
    this.highestQualification = driverMIS.highestQualification || '';
    this.bloodGroup = driverMIS.bloodGroup || '';
    this.driverStatus = driverMIS.driverStatus || '';
    this.dateOfJoining = new Date(driverMIS.dateOfJoining) || new Date();
    this.dateOfJoiningString = driverMIS.dateOfJoiningString || '';
    this.dateOfLeaving = new Date(driverMIS.dateOfLeaving) || null;
    this.dateOfLeavingString = driverMIS.dateOfLeavingString || '';
    this.localAddressAddressString = driverMIS.localAddressAddressString || '';
    this.localAddressLatLong = driverMIS.localAddressLatLong || '';
    this.localAddressCityID = driverMIS.localAddressCityID || '';
    this.localAddress = driverMIS.localAddress || '';
    this.localPincode = driverMIS.localPincode || '';
    this.permanentAddressCityID = driverMIS.permanentAddressCityID || '';
    this.permanentAddressCity = driverMIS.permanentAddressCity || '';
    this.permanentAddress = driverMIS.permanentAddress || '';
    this.permanentAddressPincode = driverMIS.permanentAddressPincode || '';
    this.mobile1 = driverMIS.mobile1 || '';
    this.mobile2 = driverMIS.mobile2 || '';
    this.hubID = driverMIS.hubID || '';
    this.hub = driverMIS.hub || '';
    this.locationID = driverMIS.locationID || '';
    this.location = driverMIS.location || '';
    this.supplierType = driverMIS.supplierType || '';
    this.supplierID = driverMIS.supplierID || '';
    this.supplier = driverMIS.supplier || '';
    this.englishSpeakingSkills = driverMIS.englishSpeakingSkills || '';
    this.referenceOf = driverMIS.referenceOf || '';
    this.rtoStateID = driverMIS.rtoStateID || 0;
    this.policeVerification = driverMIS.policeVerification || '';
    this.driverImage = driverMIS.driverImage || '';
    this.medicalInsurance = driverMIS.medicalInsurance || '';
    this.drivingSinceDate = new Date(driverMIS.drivingSinceDate) || new Date();
    this.drivingSinceDateString = driverMIS.drivingSinceDateString || '';
    this.countryCodes = driverMIS.countryCodes || '';
    this.activationStatus = driverMIS.activationStatus || '';
    this.latitude = driverMIS.latitude || '';
    this.longitude = driverMIS.longitude || '';
    this.companyName = driverMIS.companyName || '';
    this.companyID = driverMIS.companyID || '';
    this.userID = driverMIS.userID || '';
    this.driverFeedbackAverage = driverMIS.driverFeedbackAverage || '';
    this.driverFeedbackReceived = driverMIS.driverFeedbackReceived || '';
    this.driverFeedbackTotal = driverMIS.driverFeedbackTotal || '';
    this.driverFeedbackCount = driverMIS.driverFeedbackCount || '';
    this.appLoginStatus = driverMIS.appLoginStatus || '';
    this.offDuty = driverMIS.offDuty || '';
    this.appVersion = driverMIS.appVersion || '';
    this.deviceModel = driverMIS.deviceModel || '';
    this.deviceIMEI = driverMIS.deviceIMEI || '';
    this.deviceType = driverMIS.deviceType || '';
    this.driverCameraProblem = driverMIS.driverCameraProblem || '';
  }
}

