// @ts-nocheck
import { formatDate } from '@angular/common';
export class Resolution {
  dutySlipID: number;
  userID: number;
  reservationID: number;
  customerID:number;
  incidenceID: number;
  passengerID: number;
  inventoryID: number;
  driverID: number;
  incidenceDate: Date ;
  incidenceTime: Date;
  incidenceDateString: string;
  incidenceTimeString: string;
  incidencePlace: string;
  dispatchLocationID: number;
  incidenceTypeID: number;
  issueCategoryID: number;
  incidenceDetails: string;
  reportingDateString: string;
  reportingDate: Date | null;
  reportingTime: Date | null;
  reportingTimeString: string;
  reportedBy: string;
  reporterName: string;
  reportSource: string;
  reportEvidenceDoc: string;
  assignedToEmployeeID: number;
  assignedToEmployeeDepartment: string;
  openedByEmployeeID: number;
  openedByEmployeeName: string;
  openedByEmployeeDepartment: string;
  openDateString: string;
  openDate: Date | null;
  openTime: Date | null;
  openTimeString: string;
  closedByEmployeeID: number;
  closeByEmployeeName:string;
  rootCauseAnalysis: string;
  actionTaken: string;
  closureComment: string;
  closureDate: Date | null;
  closureTime: Date | null;
  closureDateString: string;
  closureTimeString: string;
  incidenceCategory: string;
  responsible1DriverID: number;
  supplierName:string;
  customerPersonName:string;
  responsible1VendorID: number;
  responsible2VendorID: number;
  responsible1EmployeeID: number;
  responsible1CustomerPersonID: number;
  responsible1CustomerPersonName:string;
  responsible1DriverName:string;
  responsible4VendorName:string;
  responsible1VendorName:string;
  responsible2: string;
  assignedToEmployeeName: string;
  dutySlipNumber: string;
  incidenceType: string;
  issueCategory: string;
  responsible2DriverID: number;
  responsible2VendorName:string;
  responsible3EmployeeName:string;
  responsible2EmployeeName:string;
  responsible1Name:number;
  responsible2EmployeeID: number;
  responsible2CustomerPersonID: number;
  responsible2DriverName:string;
  responsible2CustomerPersonName:string;
  responsible3: string;
  responsible3CustomerPersonName:string;
  responsible3VendorName:string;
  responsible3DriverName:string;
  responsible4CustomerPersonName:string;
  responsible4EmployeeName:string;
  responsible4DriverName:string;
  registrationNumber: string;
  driverName: string;
  locationOutAddressString: string;
  responsible3DriverID: number;
  responsible3VendorID: number;
  responsible3EmployeeID: number;
  responsible3CustomerPersonID: number;
  responsible4: string;
  responsible4DriverID: number;
  responsible4VendorID: number;
  responsible4EmployeeID: number;
  responsible4CustomerPersonID: number;
  activationStatus: boolean | null;
  customerName:string;
  dispatchLocation:string;
  responsible1:string;
  responsible1EmployeeName:string
  incidenceEmailAcknowledged:boolean;
  feedbackEmailAcknowledged:boolean;
  Responsible:string;
  closedByEmployee:string;
  customerpersonName:string;
  Responsible1Name:string;
  Responsible2Name:string;
  Responsible3Name:string;
  Responsible4Name:string;
  followUpAction : string;
  reminderDateForFollowUp: Date;
  reminderDateForFollowUpString : string;
  debitTypeID : number;
  debitType : string;
  debitAmount:number;
  constructor(incidence) {
    this.dutySlipID = incidence.dutySlipID || '';
    this.userID = incidence.userID || '';
    this.reservationID = incidence.reservationID || '';
    this.incidenceID = incidence.incidenceID || '';
    this.passengerID = incidence.passengerID || '';
    this.inventoryID = incidence.inventoryID || '';
    this.driverID = incidence.driverID || '';
    this.incidenceDate = incidence.incidenceDate || null;
    this.incidenceTime = incidence.incidenceTime || null;
    this.incidenceDateString = incidence.incidenceDateString || '';
    this.incidenceTimeString = incidence.incidenceTimeString || '';
    this.incidencePlace = incidence.incidencePlace || '';
    this.dispatchLocationID = incidence.dispatchLocationID || '';
    this.incidenceTypeID = incidence.incidenceTypeID || '';
    this.issueCategoryID = incidence.issueCategoryID || '';
    this.incidenceDetails = incidence.incidenceDetails || '';
    this.reportingDateString = incidence.reportingDateString || '';
    this.reportingDate = incidence.reportingDate || null;
    this.reportingTime = incidence.reportingTime || null;
    this.reportingTimeString = incidence.reportingTimeString || '';
    this.reportedBy = incidence.reportedBy || '';
    this.reporterName = incidence.reporterName || '';
    this.reportSource = incidence.reportSource || '';
    this.reportEvidenceDoc = incidence.reportEvidenceDoc || '';
    this.assignedToEmployeeID = incidence.assignedToEmployeeID || '';
   this.openedByEmployeeName = incidence.openedByEmployeeName || '';
    this.assignedToEmployeeDepartment = incidence.assignedToEmployeeDepartment || '';
    this.openedByEmployeeID = incidence.openedByEmployeeID || '';
    this.openedByEmployeeDepartment = incidence.openedByEmployeeDepartment || '';
    this.openDateString = incidence.openDateString || '';
    this.openDate = incidence.openDate || null;
    this.openTime = incidence.openTime || null;
    this.openTimeString = incidence.openTimeString || '';
    this.dispatchLocation = incidence.dispatchLocation || '';
    this.closedByEmployeeID = incidence.closedByEmployeeID || '';
    this.rootCauseAnalysis = incidence.rootCauseAnalysis || '';
    this.actionTaken = incidence.actionTaken || '';
    this.closureComment = incidence.closureComment || '';
    this.closureDate = incidence.closureDate || '';
    this.closureTime = incidence.closureTime || '';
    this.closureDateString = incidence.closureDateString || '';
    this.closureTimeString = incidence.closureTimeString || '';
    this.incidenceCategory = incidence.incidenceCategory || '';
    this.responsible1DriverID = incidence.responsible1DriverID || '';
    this.responsible1VendorID = incidence.responsible1VendorID || '';
    this.responsible1EmployeeID = incidence.responsible1EmployeeID || '';
    this.responsible1CustomerPersonID = incidence.responsible1CustomerPersonID || '';
    this.responsible2 = incidence.responsible2 || '';
    this.responsible2DriverID = incidence.responsible2DriverID || '';
    this.responsible2EmployeeID = incidence.responsible2EmployeeID || '';
    this.responsible2CustomerPersonID = incidence.responsible2CustomerPersonID || '';
    this.responsible3 = incidence.responsible3 || '';
    this.responsible3DriverID = incidence.responsible3DriverID || '';
    this.responsible3VendorID = incidence.responsible3VendorID || '';
    this.responsible3EmployeeID = incidence.responsible3EmployeeID || '';
    this.responsible3CustomerPersonID = incidence.responsible3CustomerPersonID || '';
    this.responsible4 = incidence.responsible4 || '';
    this.responsible4DriverID = incidence.responsible4DriverID || '';
    this.responsible4VendorID = incidence.responsible4VendorID || '';
    this.responsible4EmployeeID = incidence.responsible4EmployeeID || '';
    this.responsible4CustomerPersonID = incidence.responsible4CustomerPersonID || '';
    this.followUpAction = incidence.followUpAction || '';
    this.reminderDateForFollowUpString = incidence.reminderDateForFollowUpString || '';
    this.debitTypeID = incidence.debitTypeID || '';
    this.debitAmount = incidence.debitAmount || '';
    this.closureDate=new Date();
    this.closureTime=new Date();
  }
}


export class DebitTypeModel{
  debitTypeID : number;
  debitType :string;
  debitTypeAmount : number

  constructor(debitTypeModel) {
    this.debitTypeID = debitTypeModel.debitTypeID || '';
    this.debitType = debitTypeModel.debitType || '';
    this.debitTypeAmount = debitTypeModel.debitTypeAmount || '';
  }
}


