// @ts-nocheck
import { formatDate } from '@angular/common';
export class VendorLocalLumpsumRate {
  vendorLocalLumpsumRateID: number;
  vendorContractID: number;
  vendorContractCarCategoryID:number;
  vendorContractCityTiersID:number;
    vendorContractCityTier:string;
  packageID:number;
  billFromTo:string;
  minimumHours:number;
  minimumKM:number;
  baseRate:number;
  graceMinutesNightCharge:number;
  baseRateForSupplier:number;
  billingOption:string;
  extraKMRate:number;
  extraKMRateForSupplier:number;
  extraHRRate:number;
  extraHRRateForSupplier:number;
  kMsPerExtraHR:number;
  driverAllowance:number;
  driverAllowanceForSupplier:number;
  nightChargeStartTime:Date;
  nightChargeStartTimeString:string;
  nightChargeEndTime:Date;
  nightChargeEndTimeString:string;
  nightCharge:number;
  nightChargeForSupplier:number;
  graceMinutesForNightCharge:number;
  fkmP2P:number;
  graceKM:number;
  fixedP2PAmount:number;
  graceMinutesNightChargeAmount:number;
  additionalKM:number;
  additionalMinutes:number;
  tollChargeable:boolean;
  graceMinutes:number;
  parkingChargeable:boolean;
  interStateChargeable:boolean; 
  nightChargeable:boolean;
  activationStatus:boolean;
  minDays:string;
  vendorContractCarCategory:string;
  city:string;
  package:string;
  vehicleCategory:string;
  cityTier:string;
userID:number;
nightChargesBasedOn:string;
 constructor(vendorLocalLumpsumRate) {
   {
      this.vendorLocalLumpsumRateID = vendorLocalLumpsumRate.vendorLocalLumpsumRateID || -1;
      this.vendorContractID = vendorLocalLumpsumRate.vendorContractID || '';
      this.vendorContractCarCategoryID = vendorLocalLumpsumRate.vendorContractCarCategoryID || '';
      this.vendorContractCityTiersID = vendorLocalLumpsumRate.vendorContractCityTiersID || '';
      this.packageID = vendorLocalLumpsumRate.packageID || '';
      this.billFromTo = vendorLocalLumpsumRate.billFromTo || '';
      this.nightChargesBasedOn = vendorLocalLumpsumRate.nightChargesBasedOn || '';
      this.baseRateForSupplier = vendorLocalLumpsumRate.baseRateForSupplier || '';
      this.minimumHours = vendorLocalLumpsumRate.minimumHours || '';
      this.minimumKM = vendorLocalLumpsumRate.minimumKM || '';
      this.baseRate = vendorLocalLumpsumRate.baseRate || '';
      this.billingOption = vendorLocalLumpsumRate.billingOption || '';
      this.extraKMRate = vendorLocalLumpsumRate.extraKMRate || '';
      this.extraKMRateForSupplier = vendorLocalLumpsumRate.extraKMRateForSupplier || '';
      this.extraHRRate = vendorLocalLumpsumRate.extraHRRate || '';
      this.extraHRRateForSupplier = vendorLocalLumpsumRate.extraHRRateForSupplier || '';
      this.kMsPerExtraHR = vendorLocalLumpsumRate.kMsPerExtraHR || '';
      this.driverAllowance = vendorLocalLumpsumRate.driverAllowance || '';
      this.driverAllowanceForSupplier = vendorLocalLumpsumRate.driverAllowanceForSupplier || '';
      this.nightChargeStartTimeString = vendorLocalLumpsumRate.nightChargeStartTimeString || '';
      this.nightChargeEndTimeString = vendorLocalLumpsumRate.nightChargeEndTimeString || '';
      this.nightCharge = vendorLocalLumpsumRate.nightCharge || '';
      this.nightChargeForSupplier = vendorLocalLumpsumRate.nightChargeForSupplier || '';
      this.graceMinutesForNightCharge = vendorLocalLumpsumRate.graceMinutesForNightCharge || 0;
      this.fkmP2P = vendorLocalLumpsumRate.fkmP2P || 0;
      this.graceMinutes = vendorLocalLumpsumRate.graceMinutes || '';
      this.graceKM = vendorLocalLumpsumRate.graceKM || '';
      this.fixedP2PAmount = vendorLocalLumpsumRate.fixedP2PAmount || 0;
      this.graceMinutesNightChargeAmount = vendorLocalLumpsumRate.graceMinutesNightChargeAmount || 0;
      this.additionalKM = vendorLocalLumpsumRate.additionalKM || 0;
      this.additionalMinutes = vendorLocalLumpsumRate.additionalMinutes || 0;
      this.tollChargeable = vendorLocalLumpsumRate.tollChargeable || '';
      this.parkingChargeable = vendorLocalLumpsumRate.parkingChargeable || '';
      this.interStateChargeable = vendorLocalLumpsumRate.interStateChargeable || '';
      this.activationStatus = vendorLocalLumpsumRate.activationStatus || '';     
      this.nightChargeable = vendorLocalLumpsumRate.nightChargeable || '';     
      this.minDays = vendorLocalLumpsumRate.minDays || '';
      this.nightChargeStartTime=new Date();
      this.nightChargeEndTime=new Date();
   }
 }  
}

