// @ts-nocheck
import { formatDate } from '@angular/common';
export class VendorLocalTransferRate {
  vendorLocalTransferRateID: number;
  vendorContractID: number;
  vendorContractCarCategoryID:number;
  cityID:number;
  packageID:number;
  billFromTo:string;
  minimumHours:number;
  minimumKM:number;
  baseRate:number;
  graceMinutesNightCharge:number;
  baseRateForSupplier:number;
  billingOption:string;
  extraKMRate:number;
  extraKMRateForSupplier:number;
  extraHRRate:number;
  extraHRRateForSupplier:number;
  kMsPerExtraHR:number;
  driverAllowance:number;
  driverAllowanceForSupplier:number;
  nightChargeStartTime:Date;
  nightChargeStartTimeString:string;
  nightChargeEndTime:Date;
  nightChargeEndTimeString:string;
  nightCharge:number;
  nightChargeForSupplier:number;
  graceMinutesForNightCharge:number;
  fkmP2P:number;
  graceKM:number;
  fixedP2PAmount:number;
  graceMinutesNightChargeAmount:number;
  additionalKM:number;
  additionalMinutes:number;
  tollChargeable:boolean;
  graceMinutes:number;
  parkingChargeable:boolean;
  interStateChargeable:boolean; 
  nightChargeable:boolean;
  activationStatus:boolean;
  ifExtraDrivenMoveToLocalPackages:string;
  vendorContractCarCategory:string;
  city:string;
  package:string;
  vehicleCategory:string;
  cityTier:string;
userID:number;
nightChargesBasedOn:string;
 constructor(vendorLocalTransferRate) {
   {
      this.vendorLocalTransferRateID = vendorLocalTransferRate.vendorLocalTransferRateID || -1;
      this.vendorContractID = vendorLocalTransferRate.vendorContractID || '';
      this.vendorContractCarCategoryID = vendorLocalTransferRate.vendorContractCarCategoryID || '';
      this.cityID = vendorLocalTransferRate.cityID || '';
      this.packageID = vendorLocalTransferRate.packageID || '';
      this.billFromTo = vendorLocalTransferRate.billFromTo || '';
      this.nightChargesBasedOn = vendorLocalTransferRate.nightChargesBasedOn || '';
      this.baseRateForSupplier = vendorLocalTransferRate.baseRateForSupplier || '';
      this.minimumHours = vendorLocalTransferRate.minimumHours || '';
      this.minimumKM = vendorLocalTransferRate.minimumKM || '';
      this.baseRate = vendorLocalTransferRate.baseRate || '';
      this.billingOption = vendorLocalTransferRate.billingOption || '';
      this.extraKMRate = vendorLocalTransferRate.extraKMRate || '';
      this.extraKMRateForSupplier = vendorLocalTransferRate.extraKMRateForSupplier || '';
      this.extraHRRate = vendorLocalTransferRate.extraHRRate || '';
      this.extraHRRateForSupplier = vendorLocalTransferRate.extraHRRateForSupplier || '';
      this.kMsPerExtraHR = vendorLocalTransferRate.kMsPerExtraHR || '';
      this.driverAllowance = vendorLocalTransferRate.driverAllowance || '';
      this.driverAllowanceForSupplier = vendorLocalTransferRate.driverAllowanceForSupplier || '';
      this.nightChargeStartTimeString = vendorLocalTransferRate.nightChargeStartTimeString || '';
      this.nightChargeEndTimeString = vendorLocalTransferRate.nightChargeEndTimeString || '';
      this.nightCharge = vendorLocalTransferRate.nightCharge || '';
      this.nightChargeForSupplier = vendorLocalTransferRate.nightChargeForSupplier || '';
      this.graceMinutesForNightCharge = vendorLocalTransferRate.graceMinutesForNightCharge || 0;
      this.fkmP2P = vendorLocalTransferRate.fkmP2P || 0;
      this.graceMinutes = vendorLocalTransferRate.graceMinutes || '';
      this.graceKM = vendorLocalTransferRate.graceKM || '';
      this.fixedP2PAmount = vendorLocalTransferRate.fixedP2PAmount || 0;
      this.graceMinutesNightChargeAmount = vendorLocalTransferRate.graceMinutesNightChargeAmount || 0;
      this.additionalKM = vendorLocalTransferRate.additionalKM || 0;
      this.additionalMinutes = vendorLocalTransferRate.additionalMinutes || 0;
      this.tollChargeable = vendorLocalTransferRate.tollChargeable || '';
      this.parkingChargeable = vendorLocalTransferRate.parkingChargeable || '';
      this.interStateChargeable = vendorLocalTransferRate.interStateChargeable || '';
      this.activationStatus = vendorLocalTransferRate.activationStatus || '';     
      this.nightChargeable = vendorLocalTransferRate.nightChargeable || '';     
      this.ifExtraDrivenMoveToLocalPackages = vendorLocalTransferRate.ifExtraDrivenMoveToLocalPackages || '';
      this.nightChargeStartTime=new Date();
      this.nightChargeEndTime=new Date();
   }
 }  
}

