// @ts-nocheck
import { formatDate } from '@angular/common';
export class CDCLocalTransferRate {
  cdcLocalTransferRateID: number;
  customerContractID: number;
  customerContractCarCategoryID:number;
  cityID:number;
  packageID:number;
  billFromTo:string;
  minimumHours:number;
  minimumKM:number;
  baseRate:number;
  graceMinutesNightCharge:number;
  baseRateForSupplier:number;
  billingOption:string;
  extraKMRate:number;
  extraKMRateForSupplier:number;
  extraHRRate:number;
  extraHRRateForSupplier:number;
  kMsPerExtraHR:number;
  driverAllowance:number;
  driverAllowanceForSupplier:number;
  nightChargeStartTime:Date;
  nightChargeStartTimeString:string;
  nightChargeEndTime:Date;
  nightChargeEndTimeString:string;
  nightCharge:number;
  nightChargeForSupplier:number;
  graceMinutesForNightCharge:number;
  fkmP2P:number;
  graceKM:number;
  fixedP2PAmount:number;
  graceMinutesNightChargeAmount:number;
  additionalKM:number;
  additionalMinutes:number;
  tollChargeable:boolean;
  graceMinutes:number;
  parkingChargeable:boolean;
  interStateChargeable:boolean; 
  nightChargeable:boolean;
  activationStatus:boolean;
  ifExtraDrivenMoveToLocalPackages:string;
  customerContractCarCategory:string;
  city:string;
  package:string;
  vehicleCategory:string;
  cityTier:string;
userID:number;
nightChargesBasedOn:string;
 constructor(cdcLocalTransferRate) {
   {
      this.cdcLocalTransferRateID = cdcLocalTransferRate.cdcLocalTransferRateID || -1;
      this.customerContractID = cdcLocalTransferRate.customerContractID || '';
      this.customerContractCarCategoryID = cdcLocalTransferRate.customerContractCarCategoryID || '';
      this.cityID = cdcLocalTransferRate.cityID || '';
      this.packageID = cdcLocalTransferRate.packageID || '';
      this.billFromTo = cdcLocalTransferRate.billFromTo || '';
      this.nightChargesBasedOn = cdcLocalTransferRate.nightChargesBasedOn || '';
      this.baseRateForSupplier = cdcLocalTransferRate.baseRateForSupplier || '';
      this.minimumHours = cdcLocalTransferRate.minimumHours || '';
      this.minimumKM = cdcLocalTransferRate.minimumKM || '';
      this.baseRate = cdcLocalTransferRate.baseRate || '';
      this.billingOption = cdcLocalTransferRate.billingOption || '';
      this.extraKMRate = cdcLocalTransferRate.extraKMRate || '';
      this.extraKMRateForSupplier = cdcLocalTransferRate.extraKMRateForSupplier || '';
      this.extraHRRate = cdcLocalTransferRate.extraHRRate || '';
      this.extraHRRateForSupplier = cdcLocalTransferRate.extraHRRateForSupplier || '';
      this.kMsPerExtraHR = cdcLocalTransferRate.kMsPerExtraHR || '';
      this.driverAllowance = cdcLocalTransferRate.driverAllowance || '';
      this.driverAllowanceForSupplier = cdcLocalTransferRate.driverAllowanceForSupplier || '';
      this.nightChargeStartTimeString = cdcLocalTransferRate.nightChargeStartTimeString || '';
      this.nightChargeEndTimeString = cdcLocalTransferRate.nightChargeEndTimeString || '';
      this.nightCharge = cdcLocalTransferRate.nightCharge || '';
      this.nightChargeForSupplier = cdcLocalTransferRate.nightChargeForSupplier || '';
      this.graceMinutesForNightCharge = cdcLocalTransferRate.graceMinutesForNightCharge || 0;
      this.fkmP2P = cdcLocalTransferRate.fkmP2P || 0;
      this.graceMinutes = cdcLocalTransferRate.graceMinutes || '';
      this.graceKM = cdcLocalTransferRate.graceKM || '';
      this.fixedP2PAmount = cdcLocalTransferRate.fixedP2PAmount || 0;
      this.graceMinutesNightChargeAmount = cdcLocalTransferRate.graceMinutesNightChargeAmount || 0;
      this.additionalKM = cdcLocalTransferRate.additionalKM || 0;
      this.additionalMinutes = cdcLocalTransferRate.additionalMinutes || 0;
      this.tollChargeable = cdcLocalTransferRate.tollChargeable || '';
      this.parkingChargeable = cdcLocalTransferRate.parkingChargeable || '';
      this.interStateChargeable = cdcLocalTransferRate.interStateChargeable || '';
      this.activationStatus = cdcLocalTransferRate.activationStatus || '';     
      this.nightChargeable = cdcLocalTransferRate.nightChargeable || '';     
      this.ifExtraDrivenMoveToLocalPackages = cdcLocalTransferRate.ifExtraDrivenMoveToLocalPackages || '';
      this.nightChargeStartTime=new Date();
      this.nightChargeEndTime=new Date();
   }
 }  
}

