// @ts-nocheck
import { formatDate } from '@angular/common';
export class DriverCarWithoutDutyMIS {
  driverID: number;
  driverName: string;
  driverGradeID: number;
  driverFatherName: string;
  driverGrade: string;
  driverEmail: string;
  driverOfficialIdentityNumber: string;
  aadharAuthenticationToken: string;
  dob: Date;
  dobString: string;
  driverGradeName: string;
  rtoState: string;
  password: string;
  confirmPassword: string;
  idMark: string;
  localAddressCity: string;
  highestQualificationID: number;
  highestQualification: string;
  bloodGroup: string;
  driverStatus: string;
  dateOfJoining: Date;
  dateOfJoiningString: string;
  dateOfLeaving: Date;
  dateOfLeavingString: string;
  localAddressAddressString: string;
  localAddressLatLong: string;
  localAddressCityID: number;
  localAddress: string;
  localPincode: string;
  permanentAddressCityID: number;
  permanentAddressCity: string;
  permanentAddress: string;
  permanentAddressPincode: string;
  mobile1: string;
  mobile2: string;
  hubID: number;
  hub: string;
  locationID: number;
  location: string;
  supplierType: string;
  supplierTypeID: number;
  supplierID: number;
  supplier: string;
  englishSpeakingSkills: string;
  referenceOf: string;
  rtoStateID: number;
  policeVerification: string;
  driverImage: string;
  medicalInsurance: boolean;
  drivingSinceDate: Date;
  drivingSinceDateString: string;
  countryCodes: string;
  activationStatus: boolean;
  latitude: string;
  longitude: string;
  companyName: string;
  companyID: number;
  userID: number;
  driverFeedbackAverage: string;
  driverFeedbackReceived: string;
  driverFeedbackTotal: string;
  driverFeedbackCount: string;
  appLoginStatus: string;
  offDuty: string;
  appVersion: string;
  deviceModel: string;
  deviceIMEI: string;
  deviceType: string;
  driverCameraProblem: string;

  constructor(driverCarSupplierMIS: any) {
    this.driverID = driverCarSupplierMIS.driverID || -1;
    this.driverName = driverCarSupplierMIS.driverName || '';
    this.driverGradeID = driverCarSupplierMIS.driverGradeID || '';
    this.driverFatherName = driverCarSupplierMIS.driverFatherName || '';
    this.driverGrade = driverCarSupplierMIS.driverGrade || '';
    this.driverEmail = driverCarSupplierMIS.driverEmail || '';
    this.driverOfficialIdentityNumber = driverCarSupplierMIS.driverOfficialIdentityNumber || '';
    this.aadharAuthenticationToken = driverCarSupplierMIS.aadharAuthenticationToken || '';
    this.dob = new Date(driverCarSupplierMIS.dob) || new Date();
    this.dobString = driverCarSupplierMIS.dobString || '';
    this.driverGradeName = driverCarSupplierMIS.driverGradeName || '';
    this.rtoState = driverCarSupplierMIS.rtoState || '';
    this.password = driverCarSupplierMIS.password || '';
    this.confirmPassword = driverCarSupplierMIS.confirmPassword || '';
    this.idMark = driverCarSupplierMIS.idMark || '';
    this.localAddressCity = driverCarSupplierMIS.localAddressCity || '';
    this.highestQualificationID = driverCarSupplierMIS.highestQualificationID || '';
    this.highestQualification = driverCarSupplierMIS.highestQualification || '';
    this.bloodGroup = driverCarSupplierMIS.bloodGroup || '';
    this.driverStatus = driverCarSupplierMIS.driverStatus || '';
    this.dateOfJoining = new Date(driverCarSupplierMIS.dateOfJoining) || new Date();
    this.dateOfJoiningString = driverCarSupplierMIS.dateOfJoiningString || '';
    this.dateOfLeaving = new Date(driverCarSupplierMIS.dateOfLeaving) || null;
    this.dateOfLeavingString = driverCarSupplierMIS.dateOfLeavingString || '';
    this.localAddressAddressString = driverCarSupplierMIS.localAddressAddressString || '';
    this.localAddressLatLong = driverCarSupplierMIS.localAddressLatLong || '';
    this.localAddressCityID = driverCarSupplierMIS.localAddressCityID || '';
    this.localAddress = driverCarSupplierMIS.localAddress || '';
    this.localPincode = driverCarSupplierMIS.localPincode || '';
    this.permanentAddressCityID = driverCarSupplierMIS.permanentAddressCityID || '';
    this.permanentAddressCity = driverCarSupplierMIS.permanentAddressCity || '';
    this.permanentAddress = driverCarSupplierMIS.permanentAddress || '';
    this.permanentAddressPincode = driverCarSupplierMIS.permanentAddressPincode || '';
    this.mobile1 = driverCarSupplierMIS.mobile1 || '';
    this.mobile2 = driverCarSupplierMIS.mobile2 || '';
    this.hubID = driverCarSupplierMIS.hubID || '';
    this.hub = driverCarSupplierMIS.hub || '';
    this.locationID = driverCarSupplierMIS.locationID || '';
    this.location = driverCarSupplierMIS.location || '';
    this.supplierType = driverCarSupplierMIS.supplierType || '';
    this.supplierID = driverCarSupplierMIS.supplierID || '';
    this.supplier = driverCarSupplierMIS.supplier || '';
    this.englishSpeakingSkills = driverCarSupplierMIS.englishSpeakingSkills || '';
    this.referenceOf = driverCarSupplierMIS.referenceOf || '';
    this.rtoStateID = driverCarSupplierMIS.rtoStateID || 0;
    this.policeVerification = driverCarSupplierMIS.policeVerification || '';
    this.driverImage = driverCarSupplierMIS.driverImage || '';
    this.medicalInsurance = driverCarSupplierMIS.medicalInsurance || '';
    this.drivingSinceDate = new Date(driverCarSupplierMIS.drivingSinceDate) || new Date();
    this.drivingSinceDateString = driverCarSupplierMIS.drivingSinceDateString || '';
    this.countryCodes = driverCarSupplierMIS.countryCodes || '';
    this.activationStatus = driverCarSupplierMIS.activationStatus || '';
    this.latitude = driverCarSupplierMIS.latitude || '';
    this.longitude = driverCarSupplierMIS.longitude || '';
    this.companyName = driverCarSupplierMIS.companyName || '';
    this.companyID = driverCarSupplierMIS.companyID || '';
    this.userID = driverCarSupplierMIS.userID || '';
    this.driverFeedbackAverage = driverCarSupplierMIS.driverFeedbackAverage || '';
    this.driverFeedbackReceived = driverCarSupplierMIS.driverFeedbackReceived || '';
    this.driverFeedbackTotal = driverCarSupplierMIS.driverFeedbackTotal || '';
    this.driverFeedbackCount = driverCarSupplierMIS.driverFeedbackCount || '';
    this.appLoginStatus = driverCarSupplierMIS.appLoginStatus || '';
    this.offDuty = driverCarSupplierMIS.offDuty || '';
    this.appVersion = driverCarSupplierMIS.appVersion || '';
    this.deviceModel = driverCarSupplierMIS.deviceModel || '';
    this.deviceIMEI = driverCarSupplierMIS.deviceIMEI || '';
    this.deviceType = driverCarSupplierMIS.deviceType || '';
    this.driverCameraProblem = driverCarSupplierMIS.driverCameraProblem || '';
  }
}

