// @ts-nocheck
/** Column order matches DynamicsMIS API / CSV export */
export const DYNAMICS_MIS_API_COLUMNS: string[] = [
  'Billno',
  'Series',
  'BillingBranch',
  'CustomerServiceLocation',
  'GSTNo',
  'BookedBy',
  'UsedBy',
  'BillDate',
  'CustomerName',
  'Customerid',
  'CarHireCharges',
  'ParkingandToll',
  'NetCCProcessingamount',
  'SUBTOTAL',
  'NetSgstAmount',
  'NetCgstAmount',
  'NetIgstAmount',
  'FinalBillAmount',
  'SGSTRate',
  'CGSTRate',
  'IGSTRate',
  'RoundOff',
  'NARRATION',
  'BillAlter',
  'CessAmount',
  'CessPercentage',
  'IRNNO',
  'IRNDATE',
  'Segment',
  'HSNSAC',
  'ServicedateFrom',
  'ServicedateTo',
  'Previousbillno',
  'PreviousbillDate',
  'Remarks',
  'LocationBranch',
  'InvoiceID',
  'InvoiceType',
  'ValidationError'
];

/** JSON key variants per API property (camelCase + PascalCase) */
export const DYNAMICS_MIS_COLUMN_ALIASES: Record<string, string[]> = {
  Billno: ['Billno', 'billno'],
  BillingBranch: ['BillingBranch', 'billingBranch'],
  CustomerServiceLocation: ['CustomerServiceLocation', 'customerServiceLocation'],
  GSTNo: ['GSTNo', 'gstNo', 'gstNO'],
  BookedBy: ['BookedBy', 'bookedBy'],
  UsedBy: ['UsedBy', 'usedBy'],
  BillDate: ['BillDate', 'billDate'],
  CustomerName: ['CustomerName', 'customerName'],
  Customerid: ['Customerid', 'customerid', 'customerID'],
  CarHireCharges: ['CarHireCharges', 'carHireCharges'],
  ParkingandToll: ['ParkingandToll', 'parkingandToll'],
  NetCCProcessingamount: ['NetCCProcessingamount', 'netCCProcessingamount'],
  SUBTOTAL: ['SUBTOTAL', 'subtotal', 'sUBTOTAL'],
  NetSgstAmount: ['NetSgstAmount', 'netSgstAmount'],
  NetCgstAmount: ['NetCgstAmount', 'netCgstAmount'],
  NetIgstAmount: ['NetIgstAmount', 'netIgstAmount'],
  FinalBillAmount: ['FinalBillAmount', 'finalBillAmount'],
  SGSTRate: ['SGSTRate', 'sgstRate', 'sGSTRate'],
  CGSTRate: ['CGSTRate', 'cgstRate', 'cGSTRate'],
  IGSTRate: ['IGSTRate', 'igstRate', 'iGSTRate'],
  RoundOff: ['RoundOff', 'roundOff'],
  NARRATION: ['NARRATION', 'narration', 'nARRATION'],
  BillAlter: ['BillAlter', 'billAlter'],
  CessAmount: ['CessAmount', 'cessAmount'],
  CessPercentage: ['CessPercentage', 'cessPercentage'],
  IRNNO: ['IRNNO', 'irnno', 'iRNNO'],
  IRNDATE: ['IRNDATE', 'irndate', 'iRNDATE'],
  Segment: ['Segment', 'segment'],
  HSNSAC: ['HSNSAC', 'hsnsac', 'hSNSAC'],
  ServicedateFrom: ['ServicedateFrom', 'servicedateFrom'],
  ServicedateTo: ['ServicedateTo', 'servicedateTo'],
  Previousbillno: ['Previousbillno', 'previousbillno', 'previousBillno'],
  PreviousbillDate: ['PreviousbillDate', 'previousbillDate', 'previousBillDate'],
  Remarks: ['Remarks', 'remarks'],
  LocationBranch: ['LocationBranch', 'locationBranch'],
  InvoiceID: ['InvoiceID', 'invoiceID', 'invoiceId'],
  InvoiceType: ['InvoiceType', 'invoiceType'],
  Series: ['Series', 'series'],
  ValidationError: ['ValidationError', 'validationError']
};
